@startuml
class fr.unice.polytech.citadelle.output.PrintCitadels {
+ {static} void startCitadelles()
+ {static} void printRolePhase()
+ {static} String stringColoredGold(int)
+ {static} void playerStartTurn(Character,Player)
+ {static} void chooseRole(Player,Character)
+ {static} void chooseDistrict(Player,District)
+ {static} void printRanking(ArrayList<Player>)
+ {static} void dropALine()
+ {static} void printFirstPlayerToComplete(Player)
+ {static} void printPlayerToCompleteCity(Player)
+ {static} void printFitLayer()
+ {static} void printLayer()
+ {static} void printKingSpell(Player)
+ {static} void printTakeGold(Player)
+ {static} void printTakeDistrictCard(Player,District)
+ {static} void printBuildDistrict(Player,District)
+ {static} void printBoard(Board)
+ {static} void printBoardOfPlayer(Player)
+ {static} void printNumberRound(int)
+ {static} void botIsDead(Player)
+ {static} void killCharacter(Character)
+ {static} void printPhase(String,Player)
+ {static} void stealCharacter(Character,int)
+ {static} void failedToStealCharacter(Character)
+ {static} void printCharacterEarnedMoney(int,String,String)
+ {static} void printCharacterEarnedNoMoney(String,String)
+ {static} Attribute getDistrictColor(District)
+ {static} void printDistrictWithColor(Player)
+ {static} void printArchitectSpell()
+ {static} void printMagicianSpellSwapHands(Character)
+ {static} void printMagicianSpellSwapCards(ArrayList<District>)
+ {static} void printMagicianSpellFailed(Character)
+ {static} void printAddCardToTheDeck(Player,District)
+ {static} void printPutCardBackToTheDeck(Player,District)
+ {static} void printMerchantEarnedStartRoundMoney()
+ {static} void printShuffle(String)
+ {static} void printBurned(Character)
+ {static} void printAssassinAdvancedChoice(Player,int,int)
+ {static} void printThiefAdvancedChoice(Player)
+ {static} void printWarlordAdvancedChoice(Player,boolean,boolean,District)
+ {static} void printHidCharacter(Character)
+ {static} void warlordDontUseSpell(Player)
+ {static} void warlordDoHisSpell(Player,Player,District)
+ {static} void printResultOfPrediction()
+ {static} void printPlayerHasAlreadyRevealCharacter(Player,Player,Character)
}
@enduml